version: '2'
 
services:
  web1:
    build:
      context:  ./web1
      dockerfile: Dockerfile
    expose:
      - "5000"

  web2:
    build:
      context:  ./web2
      dockerfile: Dockerfile
    expose:
      - "5000"

  web3:
    build:
      context:  ./web3
      dockerfile: Dockerfile
    expose:
      - "5000"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - web1
      - web2
      - web3


